### Use H2 in-memory database by default
##spring.datasource.url=jdbc:h2:mem:towerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
##spring.datasource.driverClassName=org.h2.Driver
##spring.datasource.username=sa
##spring.datasource.password=
##
### JPA settings
##spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
##spring.jpa.hibernate.ddl-auto=update
##spring.jpa.show-sql=true
##
### Enable H2 console
##spring.h2.console.enabled=true
##spring.h2.console.path=/h2-console
##
### Thymeleaf
##spring.thymeleaf.cache=false
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/towerdb
#spring.datasource.username=root
#spring.datasource.password=Harshit1833
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#
## Thymeleaf
#spring.thymeleaf.cache=false
#
##Logging
#logging.level.root=INFO


spring.datasource.url=jdbc:mysql://tramway.proxy.rlwy.net:19927/railway
spring.datasource.username=root
spring.datasource.password=MtvGQgKJjIFvjTBXCMmveRaQkhKYUmdz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true

server.port=8080
